CONSOLETOOLS += " \ 
    lzop \
    i2c-tools \
    cpufrequtils \
    net-tools \
    wget \
    smbnetfs \
    strace \
    joe \
    nano \
    rsync \
    ethtool \
    git \
    xz \
    gnupg \
    screen \
    "
#    systemd-analyze

DEVTOOLS += " \
    gdb \
    packagegroup-core-sdk \
    python-distutils \
    gst-fsl-plugin \
    "
#    systemd-serialgetty 
#    fsl-rc-local 
SYSTEMTOOLS += " \
    networkmanager \
    python-core \
    python-re \
    python-json \
    python-pprint \
    python-netserver \
    python-netclient \
    python-compile \
    python-compiler \
    python-compression \
    python-core \
    python-curses \
    python-datetime \
    python-difflib \
    python-distutils \
    python-elementtree \
    python-email \
    python-fcntl \
    python-git \
    python-json \
    python-logging \
    python-misc \
    python-mmap \
    python-multiprocessing \
    python-netclient \
    python-netserver \
    python-pickle \
    python-pkgutil \
    python-pprint \
    python-re \
    python-rpm \
    python-shell \
    python-sqlite3 \
    python-subprocess \
    python-textutils \
    python-unittest \
    python-unixadmin \
    python-xmlrpc \
    parted \
    mariadb-client \
    watchdog \
    dropbear \
    e2fsprogs \
    par2cmdline \
    iw \
    unrar \
    procps \
    iproute2 \
    util-linux \
    util-linux-mount \
    libntfs-3g \
    ntfsprogs \
    ntfs-3g \
    "

DAEMONS += " \
    tvheadend \
    transmission \
    nzbget \
    sabnzbd \
    sabnzbd-src \
    sickbeard-git \
    transmission \
    samba \
    "    

XBMC += " \
     xbmc \
     xbmc-nm-addon \
     xbmc-image-custom-rfs \
     libbluray \
     x264 \
     lirc \ 
     shairplay \
     udev \
     " 
